#!/bin/bash
# of-env.example.sh - template for of-env.sh, the machine config of the
# openfoam-claude-suite wrappers. of-env.sh is generated by /of-setup and is
# NEVER committed. To create it by hand: copy this file to of-env.sh (beside
# the wrappers) and edit the values.
#
# The wrappers (ofrun.sh, ofcase.sh, ofmon.sh) resolve the config in order:
#   1. $OF_SUITE_ENV                              explicit path, if set
#   2. <script dir>/of-env.sh                     beside the wrappers
#   3. ~/.config/openfoam-claude-suite/of-env.sh  user-level fallback
#   4. none found -> autodetect: newest of /opt/OpenFOAM-*/etc/bashrc,
#      /usr/lib/openfoam/openfoam*/etc/bashrc
# If neither a config nor an autodetected bashrc exists, the wrappers print an
# error telling you to run /of-setup and exit 3 (__OFRC=3__).

# REQUIRED: absolute path (inside Linux/WSL) to your OpenFOAM install's
# etc/bashrc. Sourced by every wrapper before doing anything else.
OF_BASHRC=/opt/OpenFOAM-v2412/etc/bashrc

# OPTIONAL: hard cap on MPI ranks for parallel runs. "ofrun.sh par <case> <N>"
# lowers N to this value when N exceeds it; validation scripts cap nproc the
# same way. Unset = no cap.
#OF_NPROC_CAP=8
